### ISSUE TITLE
Generate fails

### ISSUE THREAD

**Issue by tbillington** [esdoc/esdoc-hosting#20]
Hi, thanks for providing this service :)

Our documentation used to generate fine, but now no longer works. Link is `git@github.com:sajari/sajari-sdk-js.git`.

I've update esdoc config to be named `.esdoc.json` and added the standard plugin. When running locally everything works.

The package.json dependencies does not include esdoc, could that be what's causing the online generator to fail?

**Comment by jundl77** [comment]
Same issue here. Locally it works too, but online I get the same error. Here is my [```esdoc.json```](https://github.com/jundl77/auto-format/blob/master/esdoc.json)

**Comment by bmaupin** [comment]
Same for https://github.com/bmaupin/js-civ5save

**Comment by DavidKk** [comment]
Same for https://github.com/DavidKk/qiniu-uploader

I can generate and upload successfully by Travis

![image](https://user-images.githubusercontent.com/4200041/30517808-526eeb22-9b9d-11e7-9312-40a24ca469d5.png)

But the docs page online is 404

And i can not generate online since months ago, whether the config file named `esdoc.json` or `.esdoc.json`, it can not be generated online

![image](https://user-images.githubusercontent.com/4200041/30517814-695862dc-9b9d-11e7-93f4-bc4748f3ba10.png)

My config file:

![image](https://user-images.githubusercontent.com/4200041/30517816-74668f0a-9b9d-11e7-966c-5f154b647cfd.png)

**Comment by Exodia** [comment]
same for https://github.com/ecomfe/uioc

**Comment by hkwu** [comment]
Still having this issue. Surprisingly, the esdoc/esdoc repo still builds fine, though I don't see anything special with its config.

**Comment by loopmode** [comment]
Might be due to the latest updates and kind of breaking changes since 1.0.0.

We need to define plugins for all kind of stuff in v1, which wasn't required before.
For example, my esdoc.json : https://github.com/loopmode/altx/blob/dev/esdoc.json
Should be rather like described in: https://www.npmjs.com/package/esdoc-ecmascript-proposal-plugin

**Comment by rbecheras** [comment]
Same here for my repo: `git@github.com:sirap-group/tinymce-plugin-headersfooters.git`

> https://github.com/sirap-group/tinymce-plugin-headersfooters

**Comment by susisu** [comment]
I have the same issue.

1. I tried to generate documentation for `git@github.com:susisu/mte-kernel.git` but I got "Fail esdoc.json. Please check esdoc.json"
2. I can generate documentation locally using v1.0.1 and even v0.5.2.

**Comment by h13i32maru** [comment]
I merged https://github.com/esdoc/esdoc-hosting/pull/21 that was created by @susisu.
Please try your repositories on doc.esdoc.org

Thanks.
